name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # 如果你的默认分支是 master，请将其改为 master

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24.13.x" # 你可以根据项目需求修改 Node 版本
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # Vite 默认打包输出的文件夹是 dist          cname: manosaba.iznomia.com # 自动配置 CNAME 记录          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
